# A wrapper template around the common .NET publish template with settings
# specific to this repo.

parameters:
  noCache: false
  internalProjectName: null
  publicProjectName: null
  linuxAmd64Pool: ""
  isInternalServicingValidation: false

stages:
- template: /eng/common/templates/stages/dotnet/publish.yml@self
  parameters:
    # This template's parameters can be passed through directly
    ${{ insert }}: ${{ parameters }}

    # Additional customizations specific to this repo
    customPublishInitSteps:
    - template: /eng/pipelines/steps/set-public-source-branch-var.yml@self
    - template: /eng/pipelines/steps/set-publish-mcrdocs-args-var.yml@self
